from typing import Any

from PyQt6 import QtGui as QtGui
from PyQt6 import QtWidgets as QtWidgets

class _QtWrapper:
    @classmethod
    def search(cls, name): ...

class _QtGuiWrapper(_QtWrapper):
    module: Any

class _QtWidgetsWrapper(_QtWrapper):
    module: Any

class _ModuleWrapper:
    def __init__(self, moduleName, classes) -> None: ...
    def search(self, cls): ...

class _CustomWidgetLoader:
    def __init__(self, package) -> None: ...
    def addCustomWidget(self, widgetClass, baseClass, module) -> None: ...
    def search(self, cls): ...

class LoaderCreatorPolicy:
    def __init__(self, package) -> None: ...
    def createQtGuiWidgetsWrappers(self): ...
    def createModuleWrapper(self, moduleName, classes): ...
    def createCustomWidgetLoader(self): ...
    def instantiate(self, clsObject, objectName, ctor_args, is_attribute: bool = ...): ...
    def invoke(self, rname, method, args): ...
    def getSlot(self, object, slotname): ...
    def asString(self, s): ...
