from .misc import Literal as Literal
from .misc import moduleMember as moduleMember

class ProxyMetaclass(type):
    def __init__(*args) -> None: ...
    def __getattribute__(cls, name): ...
    def __or__(self, r_op): ...
    def __eq__(self, other): ...
