class NoSuchClassError(Exception): ...
class NoSuchWidgetError(Exception): ...

class UIFileException(Exception):
    def __init__(self, ui_file, message, detail: str = ...) -> None: ...

class UnsupportedPropertyError(Exception): ...
class WidgetPluginError(Exception): ...
