from _typeshed import Incomplete

class IconCache:
    def __init__(self, object_factory, qtgui_module) -> None: ...
    def set_base_dir(self, base_dir) -> None: ...
    def get_icon(self, iconset): ...

class _IconSet:
    icon: Incomplete
    def __init__(self, iconset, base_dir) -> None: ...
    def set_icon(self, icon, qtgui_module) -> None: ...
    def __eq__(self, other): ...
