from typing import Any

from .exceptions import NoSuchWidgetError as NoSuchWidgetError
from .exceptions import WidgetPluginError as WidgetPluginError

widgetPluginPath: Any
MATCH: bool
NO_MATCH: bool
MODULE: int
CW_FILTER: int

class QObjectCreator:
    def __init__(self, creatorPolicy) -> None: ...
    def createQObject(self, classname, *args, **kwargs): ...
    def invoke(self, rname, method, args=...): ...
    def findQObjectType(self, classname): ...
    def getSlot(self, obj, slotname): ...
    def asString(self, s): ...
    def addCustomWidget(self, widgetClass, baseClass, module) -> None: ...
    @staticmethod
    def load_plugin(filename, plugin_globals, plugin_locals): ...
