from _typeshed import Incomplete

from .enum_map import EnumMap as EnumMap
from .exceptions import NoSuchClassError as NoSuchClassError
from .exceptions import UnsupportedPropertyError as UnsupportedPropertyError
from .icon_cache import IconCache as IconCache

logger: Incomplete
DEBUG: Incomplete
QtCore: Incomplete
QtGui: Incomplete
QtWidgets: Incomplete

def int_list(prop): ...
def float_list(prop): ...

bool_: Incomplete

def qfont_style_strategy(v): ...
def needsWidget(func): ...
def ascii_upper(s): ...

class Properties:
    factory: Incomplete
    def __init__(self, factory, qtcore_module, qtgui_module, qtwidgets_module) -> None: ...
    def set_base_dir(self, base_dir) -> None: ...
    buddies: Incomplete
    delayed_props: Incomplete
    icon_cache: Incomplete
    def reset(self) -> None: ...
    def convert(self, prop, widget: Incomplete | None = ...): ...
    def getProperty(self, elem, name, default: Incomplete | None = ...): ...
    def getAttribute(self, elem, name, default: Incomplete | None = ...): ...
    def setProperties(self, widget, elem) -> None: ...
    currentIndex: Incomplete
    currentRow: Incomplete
    showDropIndicator: Incomplete
    intValue: Incomplete
    value: Incomplete
    objectName: Incomplete
    margin: Incomplete
    leftMargin: Incomplete
    topMargin: Incomplete
    rightMargin: Incomplete
    bottomMargin: Incomplete
    spacing: Incomplete
    horizontalSpacing: Incomplete
    verticalSpacing: Incomplete
    def tabSpacing(self, widget, prop) -> None: ...
    def buddy(self, widget, prop) -> None: ...
    def geometry(self, widget, prop) -> None: ...
    def orientation(self, widget, prop) -> None: ...
    def isWrapping(self, widget, prop) -> None: ...
    def pyuicMargins(self, widget, prop) -> None: ...
    def pyuicSpacing(self, widget, prop) -> None: ...
